### ISSUE TITLE
feat(login): accept email address containing upper case letters

### ISSUE THREAD

**Issue by PatrickMi** [maevsi/maevsi#1015]
Email addresses with upper case are not accepted right now

**Comment by dargmuesli** [comment]
We could either take them as they are given or save them lowercased. I'm not sure if emails are allowed to have any uppercasing by the specification or if it is goodwill by the email providers.

**Comment by myyxl** [comment]
Apparently email addresses can be case-sensitive: https://webmasters.stackexchange.com/a/34058

> If you are storing email addresses then you probably should store them in their original case (the recipient at least) to be safe. However, always compare them case-insensitively in order to avoid duplicates.

**Comment by dargmuesli** [comment]
Thank you for that link! :rocket: 

---

> However, always compare them case-insensitively in order to avoid duplicates.

Not sure why one should try to avoid duplicates that way if right before that sentence it says that email addresses are case-sensitive. If someone knows, please enlighten my brain.

For now, I'd simply remove the case restriction as it apparently seems to lead to questionable ux.
Then we'll see how often users loose access to their login due to case-sensitivity and can give it some potential more thoughts if necessary.

**Comment by dargmuesli** [comment]
Based on https://www.dominicsayers.com/isemail/ the backend will accept any text smaller than 255 characters as email address, while the frontend shows a warning if a potentially invalid email address is detected.

For phone numbers, the backend will only accept the [E.164 format](https://wikipedia.org/wiki/E.164), for which the frontend will have to be adapted in https://github.com/maevsi/maevsi/issues/1384, a #hacktoberfest task.
