### ISSUE TITLE
bug(contacts): removing a contact results in an error

### ISSUE THREAD

**Issue by PatrickMi** [maevsi/maevsi#1302]
When trying to remove a contact from the contact book the error "update or delete on table "contact" violates foreign key constraint "invitation_contact_id_fkey" on table "invitation"" gets thrown. This happens on maev.si

**Comment by dargmuesli** [comment]
That's because you still have an invitation for that contact. For more human readable error messages & suggestions we already have https://github.com/maevsi/maevsi/issues/903. If you agree you can close this as "not planned" :raised_hands: I've added this issue in the list of things to do in the linked issue.
