### ISSUE TITLE
Bug: Username is missing from event event list

### ISSUE THREAD

**Issue by soerface** [maevsi/maevsi#1499]
![image](https://github.com/maevsi/maevsi/assets/967243/4afa0120-8bf3-4650-9990-9462c9cdbfc5)

When viewing the event list at https://maev.si/event/view/soerface, a snippet of the event text is shown.

Expected:
- The event text looks the as on the detail page

Actual:
- The text is missing my name

The name is probably a variable that is supposed to be inserted, but it is only inserted on the detail page, not in the list.

**Comment by dargmuesli** [comment]
Right, the underlying reason is that I did not differentiate between event descriptions and event invitation texts first. Invitations are not yet a proper object type on their own, but they should soon be! Ticket https://github.com/maevsi/maevsi/issues/1266 is tracking this. So I'll close this as duplicate to keep things tidy, but this issue has a way better description on what the result currently is. But having mentioned the other issue, they are now linked. Good catch!
