### ISSUE TITLE
feat(layout): make topbar fixed

### ISSUE THREAD

**Issue by PatrickMi** [maevsi/maevsi#983]
Currently the topper that shows the hamburger menu button, the maevsi logo and your profilepicture is floating when scrolling. It should be fixed to the upper edge of the screen of the device

**Comment by dargmuesli** [comment]
Let's also see if we want to do that for all versions of maevsi or the PWA version only.

**Comment by PatrickMi** [comment]
I'd say all versions

**Comment by dargmuesli** [comment]
Ok, I'd be happy to always know the why so let's talk about that in person, ya? My ideas here already:
I'd only do it for the PWA first because of limited height in 16:9 displays which would be decreased. It would need to be very slim as on YouTube or only pin an important heading like here on GitHub.

A sidebar would take more available space but I've decided against and removed maevsi's sidebar due to it taking too much space compared to its use as I saw in the user tests. I think a sidebar would make sense for pages like an administration dashboard with tools needing to be visible at all time.

But let's always have one UI/UX guy with us when discussing these design ideas 👍 for the pwa we can of course already implement it as to our consensus. For other screens maybe lets focus on other tasks first before we do something and revert it after, right?

**Comment by PatrickMi** [comment]
I'm always open to meeting in person for discussing. 
My idea is that it is good to always have the icon visible somewhere. Just like on the website from twitter, YouTube, instagram. Although Twitter and Instagram switched to a sidebar now. So even for 16:9 screens I would suggest we think about how we can make that icon visible everywhere to show the brand.

As for smartphones e.g. 9:16 screens, it seems to me like we have the same opinion. The fixed top bar is somehow standard in applications. 

But of course we can always discuss those topics in person. Also with a UI/UX Person 👍

**Comment by dargmuesli** [comment]
This is being implemented by the design team.
