### ISSUE TITLE
feat(calendar): evaluate native calendar on smartphones

### ISSUE THREAD

**Issue by PatrickMi** [maevsi/maevsi#992]
Instead of using a date-time library we could use the native browser datetime input as recommended by @kmein.

**Comment by dargmuesli** [comment]
What needs to be done for this issue to be resolved?

**Comment by PatrickMi** [comment]
I was told that it would be cool to have the native operating system calendar in the app instead of a proprietary one. To solve this issue, which is not technical, we should think about that possibility to implement the native calendar

**Comment by dargmuesli** [comment]
Let's talk with the person making that recommendation a bit more. I don't know what the native calendar might be / how a user's calendar would make sense inside a different application, i.e. maevsi.

**Comment by dargmuesli** [comment]
I've added the summary of our quick talk to the original description.

**Comment by kmein** [comment]
I meant that you could use the browser/OS's [native calendar `<input>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local) instead of relying on a third party one. This would provide a more streamlined experience and one less dependency, one less thing that can break.

Most browsers have good support for rendering their own date-picker. You can try out the example I linked to and see if it suits you.

**Comment by dargmuesli** [comment]
Good suggestion! I've just tried to break the constrained input in that example and was able to do so on Firefox (only). On Firefox I'm able to select a disabled month :thinking: I think I recall having difficulties styling the browser input so that it fits the other inputs' style. I was not sure if I like being dependent on the browser's (different) style implementation: e.g. on Firefox some values are able to be given by keyboard only, not by mouse/cursor/pointer.
So in summary, yes, we could get rid of a dependency, but would depend on multiple other implementations by the browser manufacturers. If this or that is more streamlined, I don't know. For the library we currently use, I'd know how to fix a potential buggy implementation, for the browser's one I don't. Having found one bug in the latter, I'd stay with the current implementation for now. Having a working implementation, I'd personally put effort into changing that once there is a more urgent reason. Regarding PRs: they're always welcome, but I recommend not putting too much effort into one without urgency. I'm closing this issue as not planned for now, but this can surely be reevaluated in the future! :heart:
